### ISSUE TITLE
Error AnimeSource

### ISSUE THREAD

**Issue by NoheliGT** [iseizuu/anime-wallpaper#13]
Can you help me with this error when trying to do searches?

    const wallpaper = await wall.search({ title: `${a}` }, AnimeSource.WallHaven);
                                                                       ^
Console:
TypeError: Cannot read properties of undefined (reading 'WallHaven')

**Comment by iseizuu** [comment]
hello, what version of anime-wallpaper?
do you already import the type in the variable?
example: `const { AnimeWallpaper, AnimeSource } = require('anime-wallpaper');`

**Comment by NoheliGT** [comment]
The version I'm using is: anime-wallpaper": "^1.1.1"; and yes, if I imported the variable in const { Anime Wallpaper, Anime Source } = require('anime-wallpaper');
So that's not the problem, I've been using this library for a while now but I only used it to generate random wallpapers and that works. I only have a problem with specific searches

**Comment by iseizuu** [comment]
version 1.1.1 is now deprecated, you can update to the latest version 3.1.0

**Comment by NoheliGT** [comment]
The update didn't work for me, I don't understand what the problem could be, but oh well, thanks.

node:internal/modules/cjs/loader:372
      throw err;
      ^

Error: Cannot find module 'C:\Users\Usuario PC\Documents\BOTOFICIAL\node_modules\anime-wallpaper\dist\**\*'. Please verify that the package.json has a valid "main" entry

**Comment by iseizuu** [comment]
uh, are you sure this is the latest version?

**Comment by NoheliGT** [comment]
yes

**Comment by iseizuu** [comment]
> Thanks, I already solved it with the version 2.0.0

try [v3.2.1](https://www.npmjs.com/package/anime-wallpaper/v/3.2.1), for the latest release
