### ISSUE TITLE
getting wrong images and undefined thumbnail

### ISSUE THREAD

**Issue by meanii** [iseizuu/anime-wallpaper#9]
i have searched "Call of the Night Wallpapers", and i got COD images instead, and got thumbnail: undefined

here is what i did:
```typescript
const wall = new AnimeWallpaper();
    const images = await wall.getAnimeWall1({ search: "Call of the Night Wallpapers", page: 2 })
    console.log(images)
    console.log(images.length)
```
here is screenshot of the result!
![image](https://user-images.githubusercontent.com/62683938/182964745-84209675-f925-4e9c-9c19-c10aa8aeb9aa.png)

**Comment by iseizuu** [comment]
thanks, I'll take a look and fix it ASAP

**Comment by iseizuu** [comment]
i just tried it and it works, have you installed the latest version?
![image](https://user-images.githubusercontent.com/64743287/183878989-74866e43-935a-42d3-a6bb-27c95671495f.png)
